### ISSUE TITLE
running 3cqbot via pythonanywhere task 

### ISSUE THREAD

**Issue by xelalem2022** [TBMoonwalker/3cqsbot#20]
I am trying to run a scheduled task on pythonanywhere with this command 

python3.9 /home/Zola/botdirectory/3cqsbot.py but I am getting this error 
key=config["commas"]["key"],
  File "/usr/local/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'commas'

I have set all the required value on the config files 
am I missing something

**Comment by TBMoonwalker** [comment]
have you quotes around the key/secret in the 3commas section? there is something wrong in the config.ini

**Comment by xelalem2022** [comment]
no issue when i am running is directly via console ...I just wanted to run a schedule task to re-start the script every time it crushes

**Comment by TBMoonwalker** [comment]
hmm - I'm not familiar with the Pythonanywhere service. How is the config.ini injected in the task. We have plenty of users in Discord who run the code with Pythonanywhere, can you ask the community?

**Comment by M1ch43lV** [comment]
It is not different as running from the console. I think you have put some wrong key or did not change the directory. Have you edited the file with an windows editor? Windows Editor is putting instead of LF also a CR. This might be wrong interpreted. Use Notepad++ (downloadable from windows app store).
Here an example of how to use the script on Pythonanywhere. You have to make sure, that the scheduled task changes to the directory before starting the script.
![Screenshot 2022-03-30 182012](https://user-images.githubusercontent.com/100045502/160883581-ef0e144f-1cc7-4974-95b0-6b204920fdb2.png)
However I suggest to ask these kind of question on Discord, as Github is only for bug reporting or code changes/suggestions.

**Comment by TBMoonwalker** [comment]
@xelalem2022 Is it working now for you with @M1cha3l-2022 suggestion?

**Comment by xelalem2022** [comment]
yes it is working now ..thank you very much you guys are very helpful
